
FROM golang:1.25.6

WORKDIR /app

COPY go.mod go.sum* ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/bin/api ./cmd/api

ENV PORT=8080

EXPOSE 8080

CMD ["/app/bin/api"]

