apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: paas-frontend
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: paas-frontend
  endpoints:
    - port: http                    
      path: /metrics                
      interval: 15s